spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.schemas=${DB_SCHEMA}
spring.flyway.default-schema=${DB_SCHEMA}
spring.flyway.locations=classpath:db/migration

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.default_schema=${DB_SCHEMA}

logging.level.org.springframework=WARN
logging.level.org.olaz.instasprite_be=INFO
logging.level.org.hibernate.SQL=WARN

jwt.secret-key=${JWT_SECRET_KEY}
jwt.access-token-expires=${JWT_ACCESS_EXPIRES}
jwt.refresh-token-expires=${JWT_REFRESH_EXPIRES}


google.client-id=${GOOGLE_CLIENT_ID}
google.client-secret=${GOOGLE_CLIENT_SECRET}

server.error.include-message=never
server.error.include-stacktrace=never


server.base-url=${SERVER_BASE_URL}
app.upload.base-dir=${UPLOAD_BASE_DIR}