ALTER TABLE member
ADD COLUMN image_width INT DEFAULT 1080 NOT NULL,
ADD COLUMN image_height INT DEFAULT 1080 NOT NULL;

ALTER TABLE post_image
ADD COLUMN image_width INT DEFAULT 1080 NOT NULL,
ADD COLUMN image_height INT DEFAULT 1080 NOT NULL;

